name: Build Release APK

on:
  push:
    tags: [ 'v*' ]
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up JDK 17 (or any other version)
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'gradle'

      # Decode and write the signing key from secrets
      - name: Decode signing key
        run: |
          echo "${{ secrets.SIGNING_KEY }}" | base64 --decode > keystore.jks

      # Build the APK
#      - name: Build APK
#        run: ./gradlew assembleRelease -PKEY_STORE_PASSWORD=${{ secrets.KEY_STORE_PASSWORD }} -PKEY_PASSWORD=${{ secrets.KEY_PASSWORD }} -PALIAS=${{ secrets.ALIAS }}
      - name: Build APK
        run: ./gradlew assembleRelease
        env:
          KEY_STORE_PASSWORD: ${{ secrets.KEY_STORE_PASSWORD }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          ALIAS: ${{ secrets.ALIAS }}

      - name: Get version
        id: version
        run: echo "version=$(git describe --tags --abbrev=0)" >> $GITHUB_OUTPUT

      # Sign the APK (Already handled by Gradle)
      # Upload APK as artifact
      - name: Upload Signed APK
        uses: actions/upload-artifact@v4
        with:
          name: app-${{ steps.version.outputs.version }}-release
          path: app/build/outputs/apk/release/*.apk